# Delta table Query util
DuckDB natively supports reading Delta tables using `delta_scan()`.

In [2]:
import duckdb
from pathlib import Path
from electricity_maps.config import get_settings

settings = get_settings()
DATA_DIR = settings.data_dir

In [3]:
import re

def print_sql_df(sql_query):
    # Automatically replace schema.table with delta_scan('{DATA_DIR}/schema/table')
    parsed_query = re.sub(
        r'(?i)(FROM|JOIN)\s+([a-zA-Z0-9_]+)\.([a-zA-Z0-9_]+)', 
        f"\\1 delta_scan('{DATA_DIR}/\\2/\\3')", 
        sql_query
    )
    df = duckdb.sql(parsed_query).df()
    display(df)

In [17]:
print("Gold Daily Mix Summary:")
print_sql_df('select * from gold.daily_mix_summary limit 10')

Gold Daily Mix Summary:

,zone,date,source,generation_mwh,hours_covered,percentage,zone_name,year,month
0,FR,2026-04-24,nuclear,643201.912,15,69.282506,France,2026,4
1,FR,2026-04-24,biomass,17632.842,15,1.899322,France,2026,4
2,FR,2026-04-23,biomass,10778.330,9,1.966164,France,2026,4
3,FR,2026-04-23,hydro,46508.890,9,8.484071,France,2026,4
4,FR,2026-04-23,wind,90070.145,9,16.430440,France,2026,4
5,FR,2026-04-24,solar,114504.559,15,12.333861,France,2026,4
6,FR,2026-04-24,unknown,0.000,0,0.000000,France,2026,4
7,FR,2026-04-23,coal,0.000,9,0.000000,France,2026,4
8,FR,2026-04-24,gas,6026.554,15,0.649150,France,2026,4
9,FR,2026-04-23,unknown,0.000,0,0.000000,France,2026,4

In [18]:
print("\nGold Daily Imports:")
print_sql_df("SELECT * FROM gold.daily_imports LIMIT 10")

Gold Daily Imports:

,zone,date,source_zone,import_mwh,hours_covered,zone_name,year,month
0,FR,2026-04-24,DE,23124.0,15,France,2026,4
1,FR,2026-04-23,ES,17487.0,9,France,2026,4
2,FR,2026-04-23,BE,27882.0,9,France,2026,4
3,FR,2026-04-24,CH,18997.0,15,France,2026,4
4,FR,2026-04-24,ES,31406.0,15,France,2026,4
5,FR,2026-04-23,CH,17689.0,9,France,2026,4
6,FR,2026-04-24,BE,38553.0,15,France,2026,4
7,FR,2026-04-23,DE,21197.0,9,France,2026,4

In [4]:
print("\nPipeline State (el_state):")
print_sql_df("SELECT * FROM state.el_state ORDER BY process_ts DESC")

Pipeline State (el_state):

,process,process_ts,start_timestamp,end_timestamp,status,record_count,error_message
0,silver,1777050550,2026-04-24 22:39:10.513941+05:30,2026-04-24 22:39:10.513941+05:30,R,1,None
1,bronze,1777050504,2026-04-24 22:38:24.361390+05:30,2026-04-24 22:30:00+05:30,C,2,None
2,gold,1777045214,2026-04-24 21:10:14.139309+05:30,2026-04-24 21:10:14.139309+05:30,R,1,None
3,silver,1777044781,2026-04-24 21:03:01.115612+05:30,2026-04-24 21:03:01.115612+05:30,C,1,None
4,bronze,1777044705,2026-04-24 21:01:45.865108+05:30,2026-04-24 20:30:00+05:30,C,24,None